### ISSUE TITLE
Custom Config?

### ISSUE THREAD

**Issue by martindsouza** [FOEXgmbh/apex-client-extension#2]
The `features.json` file is good for the default configuration (perhaps rename to `default.json`

Need to allow users to have their own configuration file. This file must not be part of the repo as we don't want to check it in or changes get removed by updates to the project.

**Comment by ragFOEX** [comment]
good idea!

**Comment by Dani3lSun** [comment]
We should do it like apex-frontend-boost:
https://github.com/OraOpenSource/apex-frontend-boost/blob/master/generateConfig.js
A js file which writes the default config to a "config.json" file when doing a npm install. So the main config file isn´t part of the repo any more and everyone could update this file to your own settings...
